# Generated by Django 5.0.3 on 2024-04-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatory',
            fields=[
                ('id_conv', models.AutoField(primary_key=True, serialize=False)),
                ('documento_conv', models.CharField(blank=True, max_length=500, null=True)),
                ('estado_conv', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'investigacion"."convocatoria',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_gru', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gru', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_gru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'investigacion"."grupo',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id_lin', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_lin', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_lin', models.IntegerField(blank=True, null=True)),
                ('nombre_lin', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'investigacion"."linea',
            },
        ),
        migrations.CreateModel(
            name='PaisBm',
            fields=[
                ('id_bm', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bm', models.CharField(blank=True, max_length=100, null=True)),
                ('continente_bm', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'investigacion"."pais_bm',
            },
        ),
        migrations.CreateModel(
            name='PaisSv',
            fields=[
                ('id_sv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sv', models.CharField(blank=True, max_length=100, null=True)),
                ('continente_sv', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'investigacion"."pais_sv',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id_tip', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'investigacion"."tipo_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Sublinea',
            fields=[
                ('id_sub', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_car', models.IntegerField(blank=True, null=True)),
                ('nombre_sub', models.TextField(blank=True, null=True)),
                ('descripcion_sub', models.TextField(blank=True, null=True)),
                ('estado_sub', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investigacion"."sublinea',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_equ', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_doc', models.IntegerField(blank=True, null=True)),
                ('fk_id_gru', models.ForeignKey(blank=True, db_column='fk_id_gru', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.group')),
            ],
            options={
                'db_table': 'investigacion"."equipo',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(blank=True, max_length=1000, null=True)),
                ('fk_id_car', models.IntegerField(blank=True, null=True)),
                ('fk_id_doc', models.IntegerField(blank=True, null=True)),
                ('grupo_investigacion_pro', models.CharField(blank=True, max_length=1000, null=True)),
                ('programa_pro', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_aprobacion_pro', models.DateField(blank=True, null=True)),
                ('fk_id_lin', models.IntegerField(blank=True, null=True)),
                ('fk_id_tip', models.ForeignKey(blank=True, db_column='fk_id_tip', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.projecttype')),
            ],
            options={
                'db_table': 'investigacion"."proyecto',
            },
        ),
        migrations.CreateModel(
            name='TopicBank',
            fields=[
                ('id_ban', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_doc', models.IntegerField(blank=True, null=True)),
                ('fk_id_sub', models.IntegerField(blank=True, null=True)),
                ('tema_ban', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion_ban', models.TextField(blank=True, null=True)),
                ('archivo_adjunto_ban', models.CharField(blank=True, max_length=1500, null=True)),
                ('fecha_creacion_ban', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion_ban', models.DateTimeField(blank=True, null=True)),
                ('usuario_creacion_ban', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_actualizacion_ban', models.CharField(blank=True, max_length=255, null=True)),
                ('validacion_ban', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_ban', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_id_lin', models.ForeignKey(blank=True, db_column='fk_id_lin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investigacion.linea')),
            ],
            options={
                'db_table': 'investigacion"."banco_temas',
            },
        ),
    ]
