# Generated by Django 5.0.3 on 2024-03-31 05:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id_prf', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prf', models.CharField(max_length=40)),
                ('descripcion_prf', models.TextField()),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."perfil',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_doc', models.CharField(max_length=15)),
                ('primer_apellido_doc', models.CharField(max_length=100)),
                ('segundo_apellido_doc', models.CharField(max_length=100)),
                ('nombre_doc', models.CharField(max_length=150)),
                ('abreviatura_titulo_doc', models.CharField(max_length=150)),
                ('fotografia_doc', models.CharField(max_length=255)),
                ('perfil_profesional_doc', models.TextField()),
                ('telefono_doc', models.CharField(max_length=15)),
                ('email_doc', models.CharField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator])),
                ('oficina_doc', models.CharField(max_length=250)),
                ('facebook_doc', models.CharField(max_length=500)),
                ('twitter_doc', models.CharField(max_length=500)),
                ('pagina_web_doc', models.CharField(max_length=500)),
                ('fk_id_car', models.IntegerField()),
                ('fecha_creacion_doc', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion_doc', models.DateTimeField(auto_now=True)),
                ('usuario_creacion_doc', models.CharField(max_length=100)),
                ('usuario_actualizacion_doc', models.CharField(max_length=100)),
                ('fk_id_usu', models.IntegerField()),
                ('linkedin_doc', models.CharField(max_length=150)),
                ('sexo_doc', models.CharField(max_length=15)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."docente',
            },
        ),
        migrations.CreateModel(
            name='universidad',
            fields=[
                ('id_uni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_uni', models.TextField()),
                ('direccion_uni', models.CharField(blank=True, max_length=40, null=True)),
                ('ruc_uni', models.CharField(max_length=40)),
                ('telefono_uni', models.CharField(max_length=40)),
                ('mision_uni', models.TextField()),
                ('vision_uni', models.TextField()),
                ('email_uni', models.CharField(blank=True, max_length=40, null=True)),
                ('facebook_uni', models.CharField(max_length=40)),
                ('twitter_uni', models.CharField(max_length=40)),
                ('instagram_uni', models.CharField(max_length=40)),
                ('pagina_web_uni', models.CharField(max_length=30)),
                ('sede_uni', models.CharField(max_length=50)),
                ('logo_uni', models.CharField(max_length=255)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."universidad',
            },
        ),
        migrations.CreateModel(
            name='CollegeCareer',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_fac', models.IntegerField()),
                ('nombre_car', models.CharField(max_length=200)),
                ('siglas_car', models.CharField(max_length=50)),
                ('fk_director_doc', models.CharField(max_length=100)),
                ('foto_logo_car', models.CharField(max_length=200)),
                ('telefono_car', models.CharField(max_length=150)),
                ('email_car', models.CharField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator])),
                ('fecha_creacion_car', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion_car', models.DateTimeField(auto_now=True)),
                ('usuario_creacion_car', models.CharField(max_length=100)),
                ('usuario_actualizacion_car', models.CharField(max_length=100)),
                ('mision_car', models.TextField()),
                ('vision_car', models.TextField()),
                ('fk_dir_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.teacher')),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."carrera',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('correo_usu', models.EmailField(max_length=40, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password_usu', models.TextField()),
                ('nombre_usu', models.CharField(max_length=40)),
                ('apellido_usu', models.CharField(max_length=40)),
                ('estado_usu', models.IntegerField(default=1)),
                ('fk_id_prf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.profile')),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."usuario',
            },
        ),
        migrations.CreateModel(
            name='profileUsers',
            fields=[
                ('id_perusu', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_per', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.profile')),
                ('fk_id_usu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.users')),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public"."perfil_usuario',
            },
        ),
    ]
