# Generated by Django 5.0.3 on 2024-04-08 04:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMesh',
            fields=[
                ('id_malla', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_car', models.IntegerField(blank=True, null=True)),
                ('nombre_malla', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_malla', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_malla', models.CharField(blank=True, max_length=25, null=True)),
                ('archivo_malla', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion_malla', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_malla', models.DateField(blank=True, null=True)),
                ('usuario_creacion_malla', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_actualizacion_malla', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'public"."malla_academica',
            },
        ),
        migrations.CreateModel(
            name='CollegeCareer',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_fac', models.IntegerField()),
                ('nombre_car', models.CharField(blank=True, max_length=200, null=True)),
                ('siglas_car', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_director_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_logo_car', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_car', models.CharField(blank=True, max_length=15, null=True)),
                ('email_car', models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('fecha_creacion_car', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_car', models.DateField(blank=True, null=True)),
                ('usuario_creacion_car', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion_car', models.CharField(blank=True, max_length=100, null=True)),
                ('mision_car', models.CharField(blank=True, max_length=1000, null=True)),
                ('vision_car', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'public"."carrera',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_con', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public"."contador',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_cur', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_malla', models.IntegerField(blank=True, null=True)),
                ('nombre_cur', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion_cur', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_cur', models.DateField(blank=True, null=True)),
                ('usuario_creacion_cur', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion_cur', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'public"."curso',
            },
        ),
        migrations.CreateModel(
            name='Distributive',
            fields=[
                ('id_dis', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_per', models.IntegerField(blank=True, null=True)),
                ('fk_id_mat', models.IntegerField(blank=True, null=True)),
                ('fk_id_doc', models.IntegerField(blank=True, null=True)),
                ('paralelo_dis', models.CharField(blank=True, max_length=2, null=True)),
                ('silabo_dis', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion_dis', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_dis', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'public"."distributivo',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id_fac', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fac', models.CharField(blank=True, max_length=100, null=True)),
                ('siglas_fac', models.CharField(blank=True, max_length=10, null=True)),
                ('fk_decano_fac', models.IntegerField(blank=True, null=True)),
                ('fk_vicedecano_fac', models.IntegerField(blank=True, null=True)),
                ('correo_fac', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_fac', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion_fac', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_fac', models.DateField(blank=True, null=True)),
                ('usuario_creacion_fac', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion_fac', models.CharField(blank=True, max_length=100, null=True)),
                ('mision_fac', models.CharField(blank=True, max_length=500, null=True)),
                ('vision_fac', models.CharField(blank=True, max_length=500, null=True)),
                ('logo_fac', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'public"."facultad',
            },
        ),
        migrations.CreateModel(
            name='IndividualSchedule',
            fields=[
                ('id_horaindi', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_horaindi', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_id_doc', models.IntegerField(blank=True, null=True)),
                ('fk_id_per', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion_horaindi', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion_horaindi', models.DateTimeField(blank=True, null=True)),
                ('usuario_creacion_horaindi', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion_horaindi', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'public"."horario_individual',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion_mod', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'public"."modulos',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_per', models.DateField(blank=True, null=True)),
                ('fecha_cierre_per', models.DateField(blank=True, null=True)),
                ('rango_per', models.CharField(max_length=255)),
                ('fecha_creacion_per', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_per', models.DateField(blank=True, null=True)),
                ('estado_per', models.CharField(blank=True, max_length=25, null=True)),
                ('usuario_creacion_per', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_actualizacion_per', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'public"."periodo',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id_prf', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prf', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion_prf', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'public"."perfil',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_doc', models.CharField(blank=True, max_length=15, null=True)),
                ('primer_apellido_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_doc', models.CharField(blank=True, max_length=150, null=True)),
                ('abreviatura_titulo_doc', models.CharField(blank=True, max_length=150, null=True)),
                ('fotografia_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('perfil_profesional_doc', models.TextField(blank=True, null=True)),
                ('telefono_doc', models.CharField(blank=True, max_length=15, null=True)),
                ('email_doc', models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('oficina_doc', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('pagina_web_doc', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_id_car', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion_doc', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_doc', models.DateField(blank=True, null=True)),
                ('usuario_creacion_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_id_usu', models.IntegerField(blank=True, null=True)),
                ('linkedin_doc', models.CharField(blank=True, max_length=150, null=True)),
                ('sexo_doc', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'public"."docente',
            },
        ),
        migrations.CreateModel(
            name='universidad',
            fields=[
                ('id_uni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_uni', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_uni', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc_uni', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_uni', models.CharField(blank=True, max_length=15, null=True)),
                ('mision_uni', models.CharField(blank=True, max_length=500, null=True)),
                ('vision_uni', models.CharField(blank=True, max_length=500, null=True)),
                ('email_uni', models.CharField(blank=True, max_length=30, null=True)),
                ('facebook_uni', models.CharField(blank=True, max_length=40, null=True)),
                ('twitter_uni', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram_uni', models.CharField(blank=True, max_length=40, null=True)),
                ('pagina_web_uni', models.CharField(blank=True, max_length=30, null=True)),
                ('sede_uni', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion_car', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_car', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public"."universidad',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id_seg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seg', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion_seg', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_id_mod', models.ForeignKey(blank=True, db_column='fk_id_mod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.module')),
            ],
            options={
                'db_table': 'public"."seguridad',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_prm', models.AutoField(primary_key=True, serialize=False)),
                ('permiso_visualizar_prm', models.SmallIntegerField(blank=True, null=True)),
                ('permiso_agregar', models.SmallIntegerField(blank=True, null=True)),
                ('permiso_editar', models.SmallIntegerField(blank=True, null=True)),
                ('permiso_eliminar', models.SmallIntegerField(blank=True, null=True)),
                ('permiso_imprimir', models.SmallIntegerField(blank=True, null=True)),
                ('fk_id_prf', models.ForeignKey(blank=True, db_column='fk_id_prf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.profile')),
                ('fk_id_seg', models.ForeignKey(blank=True, db_column='fk_id_seg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.security')),
            ],
            options={
                'db_table': 'public"."permisos',
            },
        ),
        migrations.CreateModel(
            name='StudentRepresentatives',
            fields=[
                ('id_repest', models.AutoField(primary_key=True, serialize=False)),
                ('primer_apellido_repest', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_repest', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_repest', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_repest', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_repest', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_repest', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_id_car', models.ForeignKey(blank=True, db_column='fk_id_car', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.collegecareer')),
            ],
            options={
                'db_table': 'public"."representantes_estudiantiles',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_est', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_est', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido_est', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_est', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_est', models.CharField(blank=True, max_length=100, null=True)),
                ('email_est', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_est', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_est', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_est', models.CharField(blank=True, max_length=100, null=True)),
                ('genero_est', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil_est', models.CharField(blank=True, max_length=100, null=True)),
                ('etnia_est', models.CharField(blank=True, max_length=100, null=True)),
                ('discapacidad_est', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia_est', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad_est', models.CharField(blank=True, max_length=150, null=True)),
                ('parroquia_est', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion_est', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_id_usu', models.IntegerField(blank=True, null=True)),
                ('fk_id_car', models.ForeignKey(blank=True, db_column='fk_id_car', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.collegecareer')),
                ('fk_id_fac', models.ForeignKey(blank=True, db_column='fk_id_fac', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.faculty')),
                ('fk_id_per', models.ForeignKey(blank=True, db_column='fk_id_per', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.period')),
            ],
            options={
                'db_table': 'public"."estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_cur', models.IntegerField(blank=True, null=True)),
                ('nombre_mat', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_mat', models.CharField(blank=True, max_length=900, null=True)),
                ('fecha_creacion_mat', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion_mat', models.DateField(blank=True, null=True)),
                ('usuario_creacion_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion_mat', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_mat', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_mat', models.CharField(blank=True, max_length=200, null=True)),
                ('fk_id_car', models.ForeignKey(blank=True, db_column='fk_id_car', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.collegecareer')),
                ('fk_id_malla', models.ForeignKey(blank=True, db_column='fk_id_malla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.academicmesh')),
                ('fk_id_doc', models.ForeignKey(blank=True, db_column='fk_id_doc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.teacher')),
            ],
            options={
                'db_table': 'public"."materia',
            },
        ),
        migrations.AddField(
            model_name='collegecareer',
            name='fk_dir_doc',
            field=models.ForeignKey(blank=True, db_column='fk_dir_doc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.teacher'),
        ),
        migrations.CreateModel(
            name='CareerArea',
            fields=[
                ('id_area_car', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area_car', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion_area_car', models.TextField(blank=True, null=True)),
                ('foto_area_car', models.CharField(blank=True, max_length=1500, null=True)),
                ('fk_id_car', models.ForeignKey(blank=True, db_column='fk_id_car', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.collegecareer')),
                ('fk_id_doc', models.ForeignKey(blank=True, db_column='fk_id_doc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.teacher')),
            ],
            options={
                'db_table': 'public"."area_carrera',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('correo_usu', models.CharField(blank=True, max_length=50, null=True)),
                ('password_usu', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_usu', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_usu', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_usu', models.IntegerField(blank=True, null=True)),
                ('fk_id_prf', models.ForeignKey(blank=True, db_column='fk_id_prf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.profile')),
            ],
            options={
                'db_table': 'public"."usuario',
            },
        ),
        migrations.CreateModel(
            name='profileUsers',
            fields=[
                ('id_perusu', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_per', models.ForeignKey(blank=True, db_column='fk_id_per', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.profile')),
                ('fk_id_usu', models.ForeignKey(blank=True, db_column='fk_id_usu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='public.users')),
            ],
            options={
                'db_table': 'public"."perfil_usuario',
            },
        ),
    ]
