# Generated by Django 5.0.3 on 2024-04-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedDocument',
            fields=[
                ('id_aso', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_doc', models.IntegerField()),
                ('fk_id_doc_asociado', models.IntegerField()),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academico"."documento_asociado',
            },
        ),
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id_adj', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_not', models.IntegerField()),
                ('nombre_adj', models.CharField(max_length=100)),
                ('documento_adj', models.CharField(max_length=100)),
                ('fecha_subida_adj', models.DateTimeField(auto_now=True)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academico"."adjunto',
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id_col', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_carp', models.IntegerField()),
                ('fk_id_usu', models.IntegerField()),
                ('entrega_col', models.CharField(max_length=15)),
                ('notificacion_col', models.CharField(max_length=10)),
                ('acceso_col', models.CharField(max_length=10)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academico"."colaborador',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_carp', models.IntegerField()),
                ('nombre_doc', models.CharField(max_length=100)),
                ('documento_doc', models.CharField(max_length=100)),
                ('descripcion_doc', models.CharField(max_length=200)),
                ('fecha_entrega_doc', models.DateField()),
                ('fecha_creacion_doc', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion_doc', models.DateTimeField(auto_now=True)),
                ('usuario_creacion_doc', models.CharField(max_length=255)),
                ('usuario_actualizacion_doc', models.CharField(max_length=255)),
                ('fk_id_usu', models.IntegerField()),
                ('publico_doc', models.CharField(max_length=10)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academico"."documento',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id_carp', models.AutoField(primary_key=True, serialize=False)),
                ('parend_id_carp', models.IntegerField()),
                ('nombre_carp', models.CharField(max_length=100)),
                ('fk_id_usu', models.IntegerField()),
                ('descripcion_carp', models.CharField(max_length=100)),
                ('fecha_cierre_carp', models.DateField(auto_now=True)),
                ('hora_cierre_carp', models.TimeField(auto_now=True)),
                ('estado_carp', models.CharField(max_length=20)),
                ('disposicion_carp', models.CharField(max_length=20)),
                ('fecha_creacion_carp', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion_carp', models.DateTimeField(auto_now=True)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academico"."carpeta',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_not', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_not', models.CharField(max_length=100)),
                ('descripcion_not', models.TextField()),
                ('imagen_not', models.CharField(max_length=100)),
                ('estado_not', models.CharField(max_length=20)),
                ('fecha_creacion_not', models.DateTimeField(auto_now=True)),
                ('flag_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academico"."noticia',
            },
        ),
    ]
